# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. What is the value of the first triangle number to have over five hundred divisors?

def nthTriangleNumber(i) 
	i*(i+1)/2
end

def numOfDivisors(i) 
	divisors = 0
	limit = Math.sqrt(i).floor
	(1..limit).each do |x|
		if i % x == 0
			divisors += 1
		end
	end
	divisors
end

divisors = 0
i = 1

until divisors*2 > 500 do
	i += 1
	divisors = numOfDivisors(nthTriangleNumber(i))
end

p nthTriangleNumber(i)

# 76576500